import test,{before,after,mock} from 'node:test';import assert from 'node:assert/strict';import mongoose from 'mongoose';import {MongoMemoryReplSet} from 'mongodb-memory-server';
process.env.ADMIN_EMAIL='admin@example.invalid';process.env.GEMINI_API_KEY='';process.env.CHAT_ENABLED='true';
mock.module('../server/config/firebaseAdmin.js',{defaultExport:()=>({verifyIdToken:async token=>{if(!['admin','viewer','other'].includes(token))throw new Error('Invalid test token');return {uid:`test-${token}`,email:`${token}@example.invalid`,name:`Test ${token}`};}})});
const {default:app}=await import('../server/app.js');const {default:User}=await import('../server/models/User.js');const {default:Match}=await import('../server/models/Match.js');const {default:Player}=await import('../server/models/Player.js');const {default:Award}=await import('../server/models/Award.js');const {default:Achievement}=await import('../server/models/Achievement.js');const {default:Vote}=await import('../server/models/Vote.js');const {default:Like}=await import('../server/models/Like.js');const {default:Gallery}=await import('../server/models/Gallery.js');const {default:ProfileChangeRequest}=await import('../server/models/ProfileChangeRequest.js');const {default:ChatMessage}=await import('../server/models/ChatMessage.js');const {syncHistory}=await import('../server/services/history.js');
let database,server,origin,p1,p2,matchId,viewer;
async function request(path,{token,method='GET',body}={}){const response=await fetch(origin+'/api'+path,{method,headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})},...(body?{body:JSON.stringify(body)}:{})});return {status:response.status,data:await response.json()};}
before(async()=>{database=await MongoMemoryReplSet.create({binary:{version:'8.2.6'},replSet:{count:1}});await mongoose.connect(database.getUri());await Promise.all([User,Match,Player,Award,Achievement,Vote,Like,Gallery,ProfileChangeRequest,ChatMessage].map(m=>m.init()));server=app.listen(0,'127.0.0.1');await new Promise(r=>server.on('listening',r));origin=`http://127.0.0.1:${server.address().port}`;for(const token of ['admin','viewer','other'])await request('/auth/me',{token});viewer=await User.findOne({firebaseUid:'test-viewer'});p1=await Player.create({name:'Test Forward'});p2=await Player.create({name:'Test Keeper'});}, {timeout:120000});
after(async()=>{await syncHistory().catch(()=>{});server?.closeAllConnections();if(server)await new Promise(r=>server.close(r));await mongoose.disconnect();await database?.stop();});
const payload=()=>({date:'2026-01-04',name:'Test Sunday',teamA:{label:'Test A',score:99},teamB:{label:'Test B',score:99},participants:[{player:String(p1._id),team:'A',rating:8.9},{player:String(p2._id),team:'B',rating:7}],events:[{player:String(p1._id),type:'goal'}]});
test('API rejects unauthenticated and viewer match writes',async()=>{assert.equal((await request('/matches',{method:'POST',body:payload()})).status,401);assert.equal((await request('/matches',{token:'viewer',method:'POST',body:payload()})).status,403);assert.equal((await request('/auth/me',{token:'invalid'})).status,401);});
test('new match requires participant ratings and derives final scores',async()=>{const bad=payload();delete bad.participants[0].rating;assert.equal((await request('/matches',{token:'admin',method:'POST',body:bad})).status,400);const good=await request('/matches',{token:'admin',method:'POST',body:payload()});assert.equal(good.status,201,JSON.stringify(good.data));assert.equal(good.data.match.teamA.score,1);assert.equal(good.data.match.teamB.score,0);assert.equal(good.data.match.participants[0].rating,8.9);matchId=good.data.match._id;});
test('legacy missing ratings survive an edit without fabrication',async()=>{const old=payload();old.participants=old.participants.map(p=>({...p,rating:null}));old.teamA.score=1;old.teamB.score=0;const stored=await Match.create(old);const update=await request(`/matches/${stored._id}`,{token:'admin',method:'PUT',body:old});assert.equal(update.status,200,JSON.stringify(update.data));assert.equal(update.data.match.participants[0].rating,null);});
test('own goals award the opponent score and persist on the participant',async()=>{const body=payload();body.participants[0].ownGoals=1;const result=await request('/matches',{token:'admin',method:'POST',body});assert.equal(result.status,201,JSON.stringify(result.data));assert.equal(result.data.match.teamA.score,0);assert.equal(result.data.match.teamB.score,1);assert.equal(result.data.match.participants.find(p=>String(p.player._id||p.player)===String(p1._id)).ownGoals,1);assert.equal(result.data.match.events.filter(e=>e.type==='goal').length,1);});
test('votes are final, only participants can receive votes, concurrent duplicate votes cannot win',async()=>{assert.equal((await request(`/matches/${matchId}/votes`,{method:'POST',body:{playerId:String(p1._id)}})).status,401);assert.equal((await request(`/matches/${matchId}/votes`,{token:'viewer',method:'POST',body:{playerId:String(new mongoose.Types.ObjectId())}})).status,400);const results=await Promise.all([1,2].map(()=>request(`/matches/${matchId}/votes`,{token:'viewer',method:'POST',body:{playerId:String(p1._id)}})));assert.deepEqual(results.map(r=>r.status).sort(),[201,409]);assert.equal(await Vote.countDocuments({match:matchId,voter:viewer._id}),1);assert.equal((await request(`/matches/${matchId}/votes`,{token:'viewer',method:'POST',body:{playerId:String(p2._id)}})).status,409);});
test('admin finalization stores permanent MOTM, blocks later votes and leaves GG unchanged',async()=>{const before=(await request(`/stats/player/${p1._id}`)).data.stats;assert.equal((await request(`/matches/${matchId}/finalize-vote`,{token:'viewer',method:'POST'})).status,403);const final=await request(`/matches/${matchId}/finalize-vote`,{token:'admin',method:'POST'});assert.equal(final.status,200,JSON.stringify(final.data));assert.equal((await request(`/matches/${matchId}/votes`,{token:'other',method:'POST',body:{playerId:String(p2._id)}})).status,409);assert.equal(await Award.countDocuments({key:`motm:${matchId}`,player:p1._id}),1);const after=(await request(`/stats/player/${p1._id}`)).data.stats;assert.deepEqual(after,before);});
test('linked-profile preference request cannot target another player and needs approval',async()=>{assert.equal((await request('/profile-requests',{token:'viewer',method:'POST',body:{playerId:String(p1._id),changes:{preferredPositions:['ST']}}})).status,403);assert.equal((await request('/profile-requests/admin/link',{token:'admin',method:'POST',body:{userId:String(viewer._id),playerId:String(p1._id)}})).status,200);assert.equal((await request('/profile-requests',{token:'viewer',method:'POST',body:{playerId:String(p2._id),changes:{preferredPositions:['ST']}}})).status,403);const rq=await request('/profile-requests',{token:'viewer',method:'POST',body:{playerId:String(p1._id),changes:{preferredPositions:['ST','LW'],clasicoSide:'Messi'}}});assert.equal(rq.status,201,JSON.stringify(rq.data));assert.deepEqual((await Player.findById(p1._id)).preferredPositions,[]);assert.equal((await request(`/profile-requests/admin/${rq.data._id}/approve`,{token:'admin',method:'POST'})).status,200);assert.deepEqual((await Player.findById(p1._id)).preferredPositions,['ST','LW']);assert.equal((await request('/profile-requests',{token:'viewer',method:'POST',body:{playerId:String(p1._id),changes:{clasicoSide:'Ronaldo'}}})).status,400);});
test('gallery associations validated; immutable likes deduplicated concurrently',async()=>{const result=await request('/gallery',{token:'viewer',method:'POST',body:{imageUrl:'https://res.cloudinary.com/test/image/upload/test.jpg',caption:'Test fixture',matchId,playerIds:[String(p1._id),String(p2._id)]}});assert.equal(result.status,201,JSON.stringify(result.data));const id=result.data._id;const results=await Promise.all([1,2,3].map(()=>request(`/interactions/gallery/${id}/like`,{token:'viewer',method:'POST'})));assert.ok(results.every(r=>r.status===200));assert.equal((await request(`/interactions/gallery/${id}`,{token:'viewer'})).data.count,1);assert.equal((await request(`/interactions/gallery/${id}/like`,{token:'viewer',method:'DELETE'})).status,404);assert.equal((await request('/gallery?page=1')).data.items[0].playerIds.length,2);});
test('chat allows three monthly messages atomically and persists only five-day chat records',async()=>{const results=await Promise.all([1,2,3,4].map(()=>request('/chat',{token:'viewer',method:'POST',body:{message:'Temporary test message'}})));assert.deepEqual(results.map(r=>r.status).sort(),[201,201,201,409]);assert.ok(results.filter(r=>r.status===201).every(r=>r.data.message?.text==='Temporary test message'));const user=await User.findById(viewer._id).lean();assert.ok(user.chatMonth);assert.equal(user.chatMessagesUsed,3);assert.ok(await ChatMessage.exists({text:'Temporary test message'}));assert.equal((await request('/chat',{token:'other'})).data.messages.length,3);assert.equal((await request('/chat',{token:'other',method:'POST',body:{message:'x'.repeat(501)}})).status,400);});
test('closed-period awards and career achievements remain immutable across subsequent corrections',async()=>{for(let i=0;i<9;i++)await Match.create({...payload(),date:new Date('2025-06-01'),teamA:{label:'A',score:1},teamB:{label:'B',score:0}});await syncHistory();const original=await Award.findOne({key:'player:2025:0'}).lean();assert.ok(original);await Match.updateMany({date:{$lt:new Date('2026-01-01')}},{$set:{'participants.0.rating':0,'participants.1.rating':10}});await syncHistory();const kept=await Award.findOne({key:'player:2025:0'}).lean();assert.equal(String(kept.player),String(original.player));assert.ok(await Achievement.exists({player:p1._id,key:'goals:10'}));});
