import test from 'node:test';
import assert from 'node:assert/strict';
import {buildStatistics,hasDefensivePerformance} from '../server/services/statistics.js';
import {prepareMatch} from '../server/services/validation.js';

const players=[{_id:'a',name:'A',position:'ST'},{_id:'b',name:'B',position:'GK'}];
const makeMatch=({date='2026-09-01',scoreA=1,scoreB=0,defenseA=8,defenseB=6,ownGoalsA=0,ownGoalsB=0,ratingA=8,ratingB=6}={})=>({
 _id:date+scoreA+scoreB+defenseA+defenseB+ownGoalsA+ownGoalsB,date,name:'QA Match',teamA:{score:scoreA},teamB:{score:scoreB},
 participants:[{player:'a',team:'A',rating:ratingA,defensivePerformance:defenseA,ownGoals:ownGoalsA},{player:'b',team:'B',rating:ratingB,defensivePerformance:defenseB,ownGoals:ownGoalsB}],
 events:scoreA>0?[{player:'a',type:'goal'}]:scoreB>0?[{player:'b',type:'goal'}]:[]
});

test('defensive performance accepts 0 and rejects out-of-range values',()=>{assert.equal(hasDefensivePerformance(0),true);assert.equal(hasDefensivePerformance(10),true);assert.equal(hasDefensivePerformance(-0.1),false);assert.equal(hasDefensivePerformance(10.1),false);assert.equal(hasDefensivePerformance('8'),false);assert.equal(hasDefensivePerformance(null),false);});
test('defensive rating uses exactly 70% performance, 25% clean sheets and 5% own-goal discipline',()=>{const matches=[makeMatch({date:'2026-09-01',defenseA:6,ownGoalsA:1}),makeMatch({date:'2026-09-02',defenseA:8}),makeMatch({date:'2026-09-03',defenseA:10})];const a=buildStatistics(players,matches,{minimumMatches:1}).find(s=>s.playerId==='a');const expected=8*.70+(20/3)*.25+((2/3)*10)*.05;assert.equal(a.defensiveRatedMatches,3);assert.equal(a.defensivePerformanceAverage,8);assert.equal(a.defensiveCleanSheetRate,2/3);assert.equal(a.defensiveOwnGoalRate,1/3);assert.ok(Math.abs(a.defensiveRating-expected)<1e-12);});
test('win rate does not affect defensive rating',()=>{const wins=Array.from({length:3},(_,i)=>makeMatch({date:`2026-09-1${i+1}`,scoreA:1,scoreB:0,defenseA:7}));const losses=Array.from({length:3},(_,i)=>makeMatch({date:`2026-09-2${i+1}`,scoreA:0,scoreB:1,defenseA:7}));const w=buildStatistics(players,wins,{minimumMatches:1}).find(s=>s.playerId==='a');const l=buildStatistics(players,losses,{minimumMatches:1}).find(s=>s.playerId==='a');assert.equal(w.defensivePerformanceAverage,l.defensivePerformanceAverage);assert.equal(w.defensiveRating,l.defensiveRating);});
test('own goals affect defensive rating only through the 5% discipline component',()=>{const base=Array.from({length:3},(_,i)=>makeMatch({date:`2026-09-0${i+1}`,defenseA:8}));const withOwnGoal=base.map((m,i)=>i===0?{...m,participants:m.participants.map(p=>p.player==='a'?{...p,ownGoals:1}:p)}:m);const noOG=buildStatistics(players,base,{minimumMatches:1}).find(s=>s.playerId==='a');const oneOG=buildStatistics(players,withOwnGoal,{minimumMatches:1}).find(s=>s.playerId==='a');assert.equal(noOG.defensivePerformanceAverage,oneOG.defensivePerformanceAverage);assert.ok(oneOG.defensiveRating<noOG.defensiveRating);assert.equal(oneOG.averageRating,noOG.averageRating-1/3);});
test('unrecorded historical defense is excluded rather than treated as zero',()=>{const matches=[makeMatch({date:'2026-09-01',defenseA:null}),makeMatch({date:'2026-09-02',defenseA:9}),makeMatch({date:'2026-09-03',defenseA:7})];const a=buildStatistics(players,matches,{minimumMatches:1}).find(s=>s.playerId==='a');assert.equal(a.defensiveRatedMatches,2);assert.equal(a.defensivePerformanceAverage,8);assert.equal(a.defensiveRating,null);});
test('three recorded defensive performances activate the defensive rating',()=>{const matches=Array.from({length:3},(_,i)=>makeMatch({date:`2026-09-0${i+1}`,defenseA:8}));const a=buildStatistics(players,matches,{minimumMatches:1}).find(s=>s.playerId==='a');assert.equal(a.defensiveRatedMatches,3);assert.equal(a.defensiveEligible,true);assert.equal(a.defensiveRating,8.5);});
test('full GG Rating requires both normal and defensive eligibility',()=>{const five=Array.from({length:5},(_,i)=>makeMatch({date:`2026-09-1${i}`,defenseA:i<2?8:null}));const a=buildStatistics(players,five).find(s=>s.playerId==='a');assert.equal(a.ratedMatches,5);assert.equal(a.eligible,true);assert.equal(a.defensiveRatedMatches,2);assert.equal(a.ggEligible,false);assert.equal(a.ggRating,null);});
test('adding a defensive score while editing a legacy match is valid and preserved',()=>{const legacy=makeMatch({defenseA:null,defenseB:null});legacy.participants=legacy.participants.map(p=>({...p,rating:null,defensivePerformance:null}));const edited={...legacy,participants:legacy.participants.map(p=>p.player==='a'?{...p,defensivePerformance:7}:p)};assert.doesNotThrow(()=>prepareMatch(edited,legacy));assert.equal(edited.participants[0].defensivePerformance,7);assert.equal(legacy.participants[0].defensivePerformance,null);});
test('event score derivation remains independent of defensive performance',()=>{const m=makeMatch({scoreA:99,scoreB:99,defenseA:2,defenseB:9});prepareMatch(m);assert.equal(m.teamA.score,1);assert.equal(m.teamB.score,0);});
