import test from 'node:test';
import assert from 'node:assert/strict';
import {buildStatistics} from '../server/services/statistics.js';
import {classifyPlayerStyles,getPlayerStyleScores} from '../server/services/playerStyles.js';

const players=[{_id:'a',name:'Attacker',position:'ST'},{_id:'b',name:'Creator',position:'CM'},{_id:'c',name:'Keeper',position:'GK'}];
const match=(i,scorer='a',assist='b',ratings={a:8.5,b:8,c:7.5},defensive={a:8,b:8,c:8})=>({_id:`m${i}`,name:`Match ${i}`,date:`2026-01-${String(i).padStart(2,'0')}`,teamA:{score:1},teamB:{score:0},participants:[{player:'a',team:'A',rating:ratings.a,defensivePerformance:defensive.a},{player:'b',team:'A',rating:ratings.b,defensivePerformance:defensive.b},{player:'c',team:'B',rating:ratings.c,defensivePerformance:defensive.c}],events:[{player:scorer,type:'goal'},{player:assist,type:'assist'}]});

test('style profiles are deterministic, sample-protected and limited to four',()=>{const matches=Array.from({length:10},(_,i)=>match(i+1));const rows=buildStatistics(players,matches);const cohort=rows.filter(s=>s.eligible);const attacker=classifyPlayerStyles(rows.find(s=>s.playerId==='a'),cohort);const again=classifyPlayerStyles(rows.find(s=>s.playerId==='a'),cohort);assert.deepEqual(attacker,again);assert.equal(attacker.status,'active');assert.ok(attacker.styles.length>=2&&attacker.styles.length<=4);assert.ok(attacker.styles.some(s=>s.key==='attacker'||s.key==='finisher'));});
test('players below the five-match eligibility sample are style developing',()=>{const rows=buildStatistics(players,[match(1),match(2),match(3),match(4)]);const result=classifyPlayerStyles(rows.find(s=>s.playerId==='a'),rows.filter(s=>s.eligible));assert.deepEqual(result,{status:'developing',styles:[]});});
test('goalkeepers receive the Wall eligibility when they have the defensive sample',()=>{const matches=Array.from({length:5},(_,i)=>{const m=match(i+1,'a','b');m.participants.find(p=>p.player==='c').team='A';return m;});const rows=buildStatistics(players,matches);const keeper=rows.find(s=>s.playerId==='c');const scores=getPlayerStyleScores(keeper,rows.filter(s=>s.eligible));const wall=scores.find(s=>s.key==='wall');assert.equal(wall.eligible,true);assert.ok(wall.score>=65);});
test('style classification is separate from GG Rating',()=>{const matches=Array.from({length:5},(_,i)=>match(i+1));const rows=buildStatistics(players,matches);const before=rows.find(s=>s.playerId==='a').ggRating;classifyPlayerStyles(rows.find(s=>s.playerId==='a'),rows.filter(s=>s.eligible));assert.equal(rows.find(s=>s.playerId==='a').ggRating,before);});
