import express from 'express';
import mongoose from 'mongoose';
import Match from '../models/Match.js';import Vote from '../models/Vote.js';import Award from '../models/Award.js';
import {requireAuth,requireAdmin,optionalAuth} from '../middleware/auth.js';
import {id,normalizeMatchScores} from '../services/statistics.js';
const router=express.Router();
const guard=fn=>async(req,res)=>{try{if(!mongoose.isValidObjectId(req.params.id))return res.status(400).json({message:'Invalid match.'});await fn(req,res);}catch(e){res.status(e.code===11000?409:e.status||500).json({message:e.code===11000?'Your vote is already recorded.':e.status?e.message:'Could not update match voting.'});}};
const fail=(message,status=400)=>{throw Object.assign(new Error(message),{status});};
export function rankedVotes(match,votes){return match.participants.map(p=>({playerId:id(p.player),name:p.player.name||id(p.player),count:votes.filter(v=>id(v.player)===id(p.player)).length,rating:p.rating??-1,goals:match.events.filter(e=>e.type==='goal'&&id(e.player)===id(p.player)).length})).sort((a,b)=>b.count-a.count||b.rating-a.rating||b.goals-a.goals||a.name.localeCompare(b.name));}
router.get('/:id',optionalAuth,guard(async(req,res)=>{const match=await Match.findById(req.params.id).populate('participants.player','name profileImage').populate('events.player','name').lean();if(!match)return res.status(404).json({message:'Match not found.'});normalizeMatchScores(match);const votes=await Vote.find({match:match._id}).lean();res.set('Cache-Control','no-store');res.json({match,voting:{counts:rankedVotes(match,votes),total:votes.length,myVote:req.user?id(votes.find(v=>id(v.voter)===id(req.user))?.player||''):null,closed:match.votingClosed,winner:match.motmWinner}});}));
router.post('/:id/votes',requireAuth,guard(async(req,res)=>{const session=await mongoose.startSession();try{await session.withTransaction(async()=>{const match=await Match.findOneAndUpdate({_id:req.params.id,votingClosed:{$ne:true}},{$inc:{voteVersion:1}},{session,new:true});if(!match)fail('Voting is closed or this match is unavailable.',409);if(!match.participants.some(p=>id(p.player)===req.body.playerId))fail('Choose a participating player.');await Vote.create([{match:match._id,voter:req.user._id,player:req.body.playerId}],{session});});res.status(201).json({message:'Your final vote has been recorded.'});}finally{await session.endSession();}}));
router.post('/:id/finalize-vote',requireAuth,requireAdmin,guard(async(req,res)=>{const session=await mongoose.startSession();try{let winner;await session.withTransaction(async()=>{const match=await Match.findOneAndUpdate({_id:req.params.id,votingClosed:{$ne:true}},{$set:{votingClosed:true},$inc:{voteVersion:1}},{session,new:true}).populate('participants.player','name');if(!match)fail('Voting is already closed or the match is unavailable.',409);const votes=await Vote.find({match:match._id}).session(session).lean();if(!votes.length)fail('At least one vote is required.',400);winner=rankedVotes(match,votes)[0];match.motmWinner=winner.playerId;await match.save({session});await Award.updateOne({key:`motm:${match._id}`},{$setOnInsert:{key:`motm:${match._id}`,type:'motm',match:match._id,year:match.date.getUTCFullYear(),player:winner.playerId,playerName:winner.name,value:winner.count,metric:'votes'}},{session,upsert:true});});res.json({winner});}finally{await session.endSession();}}));
export default router;
