import { useEffect, useMemo, useState } from 'react';
import './chat.css';
import './notifications.css';
import Modal from './Modal';
import { api, API_URL } from '../lib/api';
import { auth } from '../firebase';

const overviewSections=[
['What is GG MATCHDAY?','GG MATCHDAY is a football journal and statistics platform built to record, preserve and explore matches played by the GG community. It turns match records into player statistics, ratings, awards, history and a living football archive.'],
['Home','The Home page is the main dashboard. It highlights latest matches and news, key football statistics, player comparisons and important snapshots from the GG MATCHDAY database.'],
['Record','Editors and admins can record matches here. A match stores the date, teams, participants, positions, goals, assists, own goals and player ratings. Final scores are derived from match events, including own goals.'],
['Leaderboard','The Leaderboard turns recorded matches into player rankings. It includes performance, goals, assists, wins, clean sheets, GG Rating and other career statistics.'],
['Calendar','Calendar organizes the match archive by date. Opening a match shows its detailed teams, score, events, participants and performance information.'],
['Players','Player profiles contain football identity and career information alongside accumulated match statistics. Player Comparisons lets you compare two or three players across goals, assists, styles, results, ratings and trends.'],
['Ratings and GG Rating','GG Rating combines 40% average recorded match rating, 20% offensive rating, 20% defensive rating and 20% result score. Offensive and defensive ratings use absolute performance rates rather than player-pool benchmarks.'],
['Awards and Hall of Fame','Awards and Hall of Fame recognize long-term achievements including goals, assists, wins, clean sheets, GG Rating and Player of the Match achievements, with defined tie-breakers.'],
['Community Chat','Community Chat is the temporary social space for GG users. Each user can send up to 3 messages per calendar month. Chat messages remain visible for 5 days and are automatically removed from the database after expiry.'],
['Notifications','Notifications are official GG MATCHDAY announcements from the admin, such as new features, fixes and version additions. Each notification remains for 5 days, is then permanently deleted, and unread status is tracked separately for each user.'],
['Themes','GG MATCHDAY currently has two themes: Dark and Gold. The interface, including notification indicators, follows the selected theme.'],
['Keeping records accurate','Match data is the foundation of the website. Scores, goals, assists, own goals, ratings, awards and player statistics are connected, so official records should be corrected carefully by editors and admins.']
];

const time=value=>value?new Date(value).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'}):'';
const date=value=>new Date(value).toLocaleDateString([],{day:'numeric',month:'short',year:'numeric'});

function Overview(){return <div className="gg-overview"><div className="gg-overview-hero"><span>✦</span><div><strong>GG MATCHDAY GUIDEBOOK</strong><p>Everything you need to know about the website, its sections and how the GG football database works.</p></div></div><div className="gg-overview-list">{overviewSections.map(([title,body],i)=><article className="gg-overview-section" key={title}><span>{String(i+1).padStart(2,'0')}</span><div><h3>{title}</h3><p>{body}</p></div></article>)}</div></div>}

function Notifications({isAdmin,onUnread}){
 const [data,setData]=useState({notifications:[],unread:false}),[loading,setLoading]=useState(true),[error,setError]=useState(''),[title,setTitle]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 async function load(){try{const next=await api('/notifications');setData(next);onUnread(Boolean(next.unread));setError('')}catch(e){setError(e.message||'Could not load notifications.')}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 async function readAll(){try{await api('/notifications/read-all',{method:'POST'});setData(x=>({...x,unread:false,notifications:x.notifications.map(n=>({...n,read:true}))}));onUnread(false)}catch(e){setError(e.message||'Could not mark notifications as read.')}}
 async function publish(e){e.preventDefault();if(!title.trim()||!message.trim()||busy)return;setBusy(true);try{await api('/notifications',{method:'POST',body:{title,message}});setTitle('');setMessage('');await load()}catch(e){setError(e.message||'Could not publish notification.')}finally{setBusy(false)}}
 async function remove(id){try{await api(`/notifications/${id}`,{method:'DELETE'});await load()}catch(e){setError(e.message||'Could not delete notification.')}}
 return <div className="gg-notifications"><div className="gg-notifications-heading"><div><strong>Official updates</strong><span>Admin announcements stay visible for 5 days.</span></div>{data.notifications.some(n=>!n.read)&&<button className="text-button" type="button" onClick={readAll}>Mark all as read</button>}</div>{isAdmin&&<form className="gg-notification-compose" onSubmit={publish}><b>Admin announcement</b><input maxLength={120} value={title} onChange={e=>setTitle(e.target.value)} placeholder="Notification title"/><textarea maxLength={1000} value={message} onChange={e=>setMessage(e.target.value)} placeholder="Tell the GG community about a new feature, fix or version addition…" rows={3}/><div><small>{message.length}/1000</small><button className="save-button" disabled={busy||!title.trim()||!message.trim()}>{busy?'Publishing…':'Publish notification'}</button></div></form>}{error&&<p className="gg-chat-error" role="alert">{error}</p>}<div className="gg-notification-list">{loading?<div className="gg-notification-empty"><span>Loading…</span></div>:!data.notifications.length?<div className="gg-notification-empty"><span>✦</span><strong>No notifications</strong><p>Official GG MATCHDAY updates will appear here.</p></div>:data.notifications.map(n=><article className={`gg-notification-card${n.read?'':' unread'}`} key={n.id}><div className="gg-notification-card-top"><div><small>GG MATCHDAY</small><h3>{n.title}</h3></div>{isAdmin&&<button type="button" className="danger-button" onClick={()=>remove(n.id)}>Delete</button>}</div><p>{n.message}</p><footer><span>{date(n.createdAt)} · {n.authorName}</span>{!n.read&&<b>NEW</b>}</footer></article>)}</div></div>;
}

export default function Chat({onClose}){
 const [status,setStatus]=useState(null),[messages,setMessages]=useState([]),[text,setText]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[section,setSection]=useState('chat'),[unread,setUnread]=useState(false),[isAdmin,setIsAdmin]=useState(false);
 useEffect(()=>{api('/auth/me').then(x=>setIsAdmin(x.user?.role==='admin')).catch(()=>{});const abort=new AbortController();let connected=true;api('/chat').then(setStatus).catch(e=>setError(e.message));(async()=>{try{const token=await auth.currentUser.getIdToken();const response=await fetch(`${API_URL}/chat/stream`,{signal:abort.signal,headers:{Authorization:`Bearer ${token}`}});if(!response.ok)throw new Error((await response.json()).message);const reader=response.body.getReader(),decoder=new TextDecoder();let buffer='';while(connected){const {value,done}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const parts=buffer.split('\n\n');buffer=parts.pop();for(const part of parts){if(!part.startsWith('data: '))continue;const msg=JSON.parse(part.slice(6));setMessages(old=>[...old.filter(m=>m.id!==msg.id&&m.expiresAt>Date.now()),msg].sort((a,b)=>a.createdAt-b.createdAt).slice(-50))}}}catch(e){if(e.name!=='AbortError')setError(e.message)}})();const timer=setInterval(()=>setMessages(old=>old.filter(m=>m.expiresAt>Date.now())),1000);return()=>{connected=false;abort.abort();clearInterval(timer)}},[]);
 async function send(e){e.preventDefault();if(!text.trim()||busy||status?.messagesRemaining===0)return;setBusy(true);try{const next=await api('/chat',{method:'POST',body:{message:text}});setStatus(next);setMessages(old=>[...old.filter(m=>m.id!==next.message?.id&&m.expiresAt>Date.now()),...(next.message?[next.message]:[])].sort((a,b)=>a.createdAt-b.createdAt).slice(-50));setText('');setError('')}catch(e){setError(e.message);try{setStatus(await api('/chat'))}catch{}}finally{setBusy(false)}}
 const remaining=status?.messagesRemaining??0,limitLabel=useMemo(()=>`${remaining} message${remaining===1?'':'s'} remaining this month`,[remaining]);
 function select(next){setSection(next);if(next==='notifications')window.dispatchEvent(new Event('gg-notifications-opened'))}
 return <Modal title="Community chat" onClose={onClose}><div className="gg-chat"><div className="gg-chat-tabs" role="tablist"><button role="tab" aria-selected={section==='chat'} className={section==='chat'?'active':''} onClick={()=>select('chat')}>Community chat</button><button role="tab" aria-selected={section==='notifications'} className={`${section==='notifications'?'active':''}${unread?' has-unread':''}`} onClick={()=>select('notifications')}>Notifications{unread&&<span className="gg-tab-dot"/>}</button><button role="tab" aria-selected={section==='overview'} className={section==='overview'?'active':''} onClick={()=>select('overview')}>Overview</button></div>{section==='chat'&&<><div className="gg-chat-intro"><div><strong>GG Community</strong><span>Messages stay visible for 5 days.</span></div><span className="gg-chat-quota">{limitLabel}</span></div>{error&&<p className="gg-chat-error" role="alert">{error}</p>}<div className="gg-chat-stream" aria-live="polite">{messages.length===0?<div className="gg-chat-empty"><span>✦</span><strong>No messages yet</strong><p>Start the conversation with the GG community.</p></div>:messages.map((m,i)=>{const grouped=i>0&&messages[i-1].name===m.name;return <article className={`gg-chat-message${grouped?' grouped':''}`} key={m.id}>{!grouped&&<div className="gg-chat-message-head"><strong>{m.name}</strong><time>{time(m.createdAt)}</time></div>}<p>{m.text}</p></article>})}</div><form className="gg-chat-composer" onSubmit={send}><textarea maxLength={500} value={text} disabled={!status||remaining===0||busy} onChange={e=>setText(e.target.value)} placeholder={remaining===0?'Monthly message limit reached':'Write a message…'} rows={2}/><div className="gg-chat-composer-footer"><small>{text.length}/500</small><button className="save-button gg-chat-send" disabled={!status||remaining===0||!text.trim()||busy}>{busy?'Sending…':'Send'}</button></div></form>{status?.messagesRemaining===0&&<p className="gg-chat-limit">You’ve used all 3 messages for {status.monthKey}. Your allowance resets next month.</p>}</>}{section==='notifications'&&<Notifications isAdmin={isAdmin} onUnread={setUnread}/>} {section==='overview'&&<Overview/>}</div></Modal>;
}
