import {useEffect,useState} from 'react';
import {createPortal} from 'react-dom';
import Modal from './Modal';
import useResource from './useResource';
import {Status,PlayerButton} from './common';
import './home-analytics.css';
function findOverviewHost(){if(typeof document==='undefined')return null;return [...document.querySelectorAll('div,section')].find(el=>{const children=[...el.children];if(children.length<3||children.length>4)return false;const labels=children.map(c=>c.textContent.trim().toUpperCase());return labels.some(t=>/^PLAYERS\s*\d+/.test(t))&&labels.some(t=>/^MATCHES\s*\d+/.test(t))&&labels.some(t=>/^GOALS\s*\d+/.test(t));})||null;}
function navigate(label){const button=[...document.querySelectorAll('button')].find(b=>b.textContent.trim().toLowerCase()===label.toLowerCase());button?.click();}
function formatSeason(season){return season.status==='live'?'Live season':'Archived season';}
export default function HomeAnalyticsHub(){const {data:seasonData,error:seasonError,loading:seasonLoading}=useResource('/stats/seasons');const {data:goalData,error:goalError,loading:goalLoading}=useResource('/stats/goals');const [host,setHost]=useState(null);const [popup,setPopup]=useState(null);const [goalOpen,setGoalOpen]=useState(false);const seasons=seasonData?.seasons||[];const goals=goalData?.records||[];
 useEffect(()=>{let frame;const locate=()=>{const next=findOverviewHost();if(next){setHost(next);return;}frame=requestAnimationFrame(locate);};locate();return()=>cancelAnimationFrame(frame);},[]);
 useEffect(()=>{if(!host)return;const children=[...host.children];const goalCard=children.find(c=>/^GOALS\s*\d+/i.test(c.textContent.trim()));const playerCard=children.find(c=>/^PLAYERS\s*\d+/i.test(c.textContent.trim()));const matchCard=children.find(c=>/^MATCHES\s*\d+/i.test(c.textContent.trim()));const makeClickable=(el,handler)=>{if(!el)return()=>{};el.classList.add('home-stat-actionable');el.setAttribute('role','button');el.setAttribute('tabindex','0');const click=()=>handler();const key=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();handler();}};el.addEventListener('click',click);el.addEventListener('keydown',key);return()=>{el.removeEventListener('click',click);el.removeEventListener('keydown',key);el.classList.remove('home-stat-actionable');el.removeAttribute('role');el.removeAttribute('tabindex');};};const cleanGoal=makeClickable(goalCard,()=>setGoalOpen(true));const cleanPlayer=makeClickable(playerCard,()=>navigate('Players'));const cleanMatch=makeClickable(matchCard,()=>navigate('Record'));return()=>{cleanGoal();cleanPlayer();cleanMatch();};},[host]);
 const card=host?createPortal(<button type="button" className="home-stat-card home-season-stat" onClick={()=>setPopup('seasons')} aria-label={`Seasons, ${seasons.length} recorded`}><span>SEASONS</span><strong>{seasonLoading?'…':seasons.length}</strong></button>,host):null;
 const goalPanel=goalOpen&&createPortal(<div className="home-goals-floating"><div className="home-goals-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setGoalOpen(false)}/><section className="home-goals-panel" role="dialog" aria-modal="true" aria-label="Goal leaders"><header><div><p className="eyebrow">GG MATCHDAY</p><h3>Goal Leaders</h3><p className="muted">All-time goals · highest to lowest</p></div><button className="compare-close" type="button" onClick={()=>setGoalOpen(false)} aria-label="Close goal leaders">×</button></header>{goalLoading||goalError?<Status loading={goalLoading} error={goalError}/>:!goals.length?<Status empty="No goals recorded yet."/>:<div className="goal-leader-list">{goals.map((player,index)=><div className="goal-leader-row" key={player.playerId}><span className="goal-rank">{index+1}</span><PlayerButton player={player}/><strong>{player.goals}</strong></div>)}</div>}</section></div>,document.body);
 return <>{card}{goalPanel}{popup==='seasons'&&<Modal title="GG Seasons" onClose={()=>setPopup(null)}><div className="season-list">{seasonError?<Status error={seasonError}/>:seasonLoading?<Status loading/>:!seasons.length?<Status empty="No seasons recorded yet."/>:seasons.map(season=><button type="button" className="season-card" key={season.year} onClick={()=>setPopup(`season-${season.year`)}><div><p className="eyebrow">{season.year} SEASON</p><strong>{formatSeason(season)}</strong></div><div className="season-meta"><span>{season.players} Players</span><span>{season.matches} Matches</span><span>{season.goals} Goals</span></div></button>)}</div></Modal>}{typeof popup==='string'&&popup.startsWith('season-')&&(()=>{const year=Number(popup.slice(7)),season=seasons.find(s=>s.year===year);return <Modal title={`${year} Season`} onClose={()=>setPopup('seasons')}>{!season?<Status empty="Season not found."/>:<div className="season-detail"><div className="season-detail-stats"><div><strong>{season.matches}</strong><span>Matches</span></div><div><strong>{season.players}</strong><span>Players</span></div><div><strong>{season.goals}</strong><span>Goals</span></div></div><p className="season-status">{season.status==='live'?'🟡 Current season · awards are provisional until finalized.':'✓ Archived season'}</p><h3>Awards</h3>{season.awards?.length?<div className="season-awards">{season.awards.map(a=><div className="gg-ranking" key={`${a.type}-${a.playerId}`}><span>🏆 {a.type==='player'?'Player of the Year':a.type==='offensive'?'Best Offensive Player':a.type==='defensive'?'Best Defensive Player':a.type==='golden-boot'?'Golden Boot':a.type==='assist-leader'?'Assist Leader':a.type}</span><strong>{a.playerName}</strong></div>)}</div>:<p className="muted">No finalized awards recorded for this season yet.</p>}</div>}</Modal>})()}</>;
}