// GG ratings are absolute performance ratings. No live player-pool percentile normalization.
export const id = value => String(value?._id ?? value);
export const isClasico = name => /\bel\s+clasico\b/.test(String(name || "").normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().replace(/[^a-z0-9]+/g, " "));
export const round = n => Number(n.toFixed(2));
export const hasRating = value => typeof value === "number" && Number.isFinite(value) && value >= 0 && value <= 10;
export const absoluteRateScore = rate => 10 * (1 - Math.exp(-Math.max(0,Number(rate) || 0)));
export const compareByGG = (a,b) => (b.ggRating ?? -1)-(a.ggRating ?? -1) || (b.averageRating ?? -1)-(a.averageRating ?? -1);
export const sortOverall = (a,b) => compareByGG(a,b) || b.winRate-a.winRate || b.goalContributions-a.goalContributions || b.cleanSheetRate-a.cleanSheetRate || b.matches-a.matches || a.name.localeCompare(b.name) || a.playerId.localeCompare(b.playerId);
export const sortOffensive = (a,b) => (b.offensiveRating ?? -1)-(a.offensiveRating ?? -1) || b.goals-a.goals || b.assists-a.assists || (b.averageRating ?? -1)-(a.averageRating ?? -1) || b.matches-a.matches || a.name.localeCompare(b.name);
export const sortDefensive = (a,b) => (b.defensiveRating ?? -1)-(a.defensiveRating ?? -1) || b.cleanSheetRate-a.cleanSheetRate || b.cleanSheets-a.cleanSheets || b.winRate-a.winRate || (b.averageRating ?? -1)-(a.averageRating ?? -1) || a.name.localeCompare(b.name);
export const sortMostWins = (a,b) => b.wins-a.wins || compareByGG(a,b) || b.goalContributions-a.goalContributions || b.matches-a.matches || a.name.localeCompare(b.name) || a.playerId.localeCompare(b.playerId);
export const sortGoldenBoot = (a,b) => b.goals-a.goals || compareByGG(a,b) || b.assists-a.assists || a.name.localeCompare(b.name) || a.playerId.localeCompare(b.playerId);
export const sortPlaymaker = (a,b) => b.assists-a.assists || compareByGG(a,b) || b.goals-a.goals || a.name.localeCompare(b.name) || a.playerId.localeCompare(b.playerId);
export function getMatchScores(match){const participants=Array.isArray(match?.participants)?match.participants:[],events=Array.isArray(match?.events)?match.events:[];const side=new Map(participants.map(p=>[id(p.player),p.team]));const normalA=events.filter(e=>e?.type==='goal'&&side.get(id(e.player))==='A').length;const normalB=events.filter(e=>e?.type==='goal'&&side.get(id(e.player))==='B').length;const ownA=participants.reduce((n,p)=>n+(p.team==='A'?Math.max(0,Number(p.ownGoals||0)):0),0);const ownB=participants.reduce((n,p)=>n+(p.team==='B'?Math.max(0,Number(p.ownGoals||0)):0),0);return {teamA:normalA+ownB,teamB:normalB+ownA};}
export function normalizeMatchScores(match){const hasEvents=Array.isArray(match?.events)&&match.events.length>0;const hasOwnGoals=Array.isArray(match?.participants)&&match.participants.some(participant=>Number(participant.ownGoals||0)>0);if(!hasEvents&&!hasOwnGoals)return match;const scores=getMatchScores(match);if(match?.teamA)match.teamA.score=scores.teamA;if(match?.teamB)match.teamB.score=scores.teamB;return match;}
export function dateQuery(year,month) { if (!year) return {}; year=Number(year); month=month == null ? null : Number(month); if (!Number.isInteger(year)||year<2000||year>2100||(month!==null&&(!Number.isInteger(month)||month<1||month>12))) throw new Error("Choose a valid year and month."); return {date:{$gte:new Date(Date.UTC(year,month ? month-1 : 0,1)),$lt:new Date(Date.UTC(month ? year : year+1,month || 0,1))}}; }
export function inPeriod(matches,year,month) { const q=dateQuery(year,month).date; return q ? matches.filter(m=>new Date(m.date)>=q.$gte&&new Date(m.date)<q.$lt) : matches; }
const matchChronology = (a,b) => new Date(b.date)-new Date(a.date) || new Date(b.createdAt || 0)-new Date(a.createdAt || 0) || id(b).localeCompare(id(a));
export function buildStatistics(players,matches,{minimumMatches=5}={}) {
 const stats=new Map(players.map(p=>[id(p),{playerId:id(p),name:p.name,profileImage:p.profileImage,position:p.position,preferredPositions:p.preferredPositions||[],clasicoSide:p.clasicoSide||"",matches:0,wins:0,draws:0,losses:0,goals:0,assists:0,ownGoals:0,cleanSheets:0,ratedMatches:0,ratingTotal:0,ratingValues:[],recent:[]} ]));
 for(const original of [...matches].sort(matchChronology)) { const scores=getMatchScores(original); for(const part of original.participants||[]) { const s=stats.get(id(part.player)); if(!s) continue; const own=Number(part.team==='A'?scores.teamA:scores.teamB),against=Number(part.team==='A'?scores.teamB:scores.teamA); const result=own>against?'W':own===against?'D':'L'; s.matches++; s[result==='W'?'wins':result==='D'?'draws':'losses']++; if(against===0)s.cleanSheets++; const ownGoals=Number(part.ownGoals||0); s.ownGoals+=Number.isFinite(ownGoals)&&ownGoals>0?ownGoals:0; if(hasRating(part.rating)){s.ratedMatches++;s.ratingTotal+=Math.max(0,part.rating-(Number.isFinite(ownGoals)?ownGoals:0));s.ratingValues.push(Math.max(0,part.rating-(Number.isFinite(ownGoals)?ownGoals:0)));} if(s.recent.length<5)s.recent.push({matchId:id(original),date:original.date,result}); } for(const e of original.events||[]){const s=stats.get(id(e.player));if(s&&['goal','assist'].includes(e.type))s[e.type==='goal'?'goals':'assists']++;} }
 const rows=[...stats.values()];
 for(const s of rows){s.goalContributions=s.goals+s.assists;s.winRate=s.matches?s.wins/s.matches:0;s.lossRate=s.matches?s.losses/s.matches:0;s.cleanSheetRate=s.matches?s.cleanSheets/s.matches:0;s.averageRating=s.ratedMatches?s.ratingTotal/s.ratedMatches:null;s.performanceRating=s.averageRating;s.resultScore=s.matches?5+(s.winRate-s.lossRate)*5:null;s.goalRate=s.matches?s.goals/s.matches:0;s.assistRate=s.matches?s.assists/s.matches:0;s.contributionRate=s.matches?s.goalContributions/s.matches:0;const goalScore=absoluteRateScore(s.goalRate);const assistScore=absoluteRateScore(s.assistRate);s.offensiveRaw=0.65*goalScore+0.35*assistScore;const cleanSheetScore=absoluteRateScore(s.cleanSheetRate);const winScore=absoluteRateScore(s.winRate);const performanceScore=s.averageRating??0;s.defensiveRaw=0.50*cleanSheetScore+0.30*winScore+0.20*performanceScore;s.eligible=s.matches>=minimumMatches;s.offensiveRating=s.eligible?s.offensiveRaw:null;s.defensiveRating=s.eligible?s.defensiveRaw:null;s.form=s.recent.length?Math.round(100*s.recent.reduce((n,r)=>n+(r.result==='W'?1:r.result==='D'?.5:0),0)/s.recent.length):null;const mean=s.averageRating;const variance=s.ratingValues.length>1&&mean!==null?s.ratingValues.reduce((n,v)=>n+(v-mean)**2,0)/s.ratingValues.length:0;s.ratingConsistency=s.ratingValues.length>=5?Math.max(0,Math.min(100,100-(Math.sqrt(variance)/5)*100)):null;delete s.ratingTotal;delete s.ratingValues;}
 for(const s of rows){s.ggRating=s.eligible&&s.averageRating!==null?round(s.averageRating*.4+s.offensiveRating*.2+s.defensiveRating*.2+s.resultScore*.2):null;s.minimumMatches=minimumMatches;}
 return rows.sort(sortOverall).map((s,i)=>({...s,rank:s.ggRating===null?null:i+1}));
}
export const milestoneRules={goals:[1,10,25,50,100,150,200],assists:[1,10,25,50,100],matches:[10,25,50,100,200,500],cleanSheets:[1,10,25,50,100]};
export function milestones(stats){return Object.entries(milestoneRules).map(([key,levels])=>{const value=stats[key],next=levels.find(n=>n>value)??Math.ceil((value+1)/100)*100;return {key,value,next,progress:Math.min(100,Math.round(100*value/next))};});}
export function selectAwards(players,matches,{year,month}={}) { const period=inPeriod(matches,year,month), min=month?3:5, rows=buildStatistics(players,period,{minimumMatches:min}); const rated=rows.filter(s=>s.ggRating!==null), eligible=rows.filter(s=>s.eligible); const selections=[['player',rated[0],'ggRating'],['offensive',[...eligible].sort(sortOffensive)[0],'offensiveRating'],['defensive',[...eligible].sort(sortDefensive)[0],'defensiveRating']]; if(!month){const cs=buildStatistics(players,period.filter(m=>isClasico(m.name)),{minimumMatches:3});selections.push(['golden-boot',[...eligible].filter(s=>s.goals>0).sort(sortGoldenBoot)[0],'goals'],['assist-leader',[...eligible].filter(s=>s.assists>0).sort(sortPlaymaker)[0],'assists'],['clasico',cs.find(s=>s.ggRating!==null),'ggRating']);} return selections.filter(([,s])=>s).map(([type,s,key])=>({type,year:Number(year),month:month?Number(month):null,player:s.playerId,playerName:s.name,value:round(s[key]),metric:key})); }