import {lazy, Suspense, useCallback} from 'react';
import Squad from './components/Squad';
import LeaderboardView from './components/Leaderboard';
import ProfileInsights from './components/ProfileInsights';
import PlayerStyles from './components/PlayerStyles';
import Clasico from './components/Clasico';
import PlayerComparisons from './components/PlayerComparisons';
import {api, invalidate} from './lib/api';
const Awards = lazy(()=>import('./components/Awards'));
const MatchDetail = lazy(()=>import('./components/MatchDetail'));
const HallOfFame = lazy(()=>import('./components/HallOfFame'));
const Chat = lazy(()=>import('./components/Chat'));

import {useEffect,useMemo,useState} from "react";
import {onAuthStateChanged,signInWithPopup,signInWithRedirect,signOut} from "firebase/auth";
import {auth,googleProvider} from "./firebase";

const API_URL=import.meta.env.VITE_API_URL||"http://localhost:5000/api";
const TABS={HOME:"home",RECORD:"record",LEADERBOARD:"leaderboard",CALENDAR:"calendar",PLAYERS:"players",ADMIN:"admin"};
function toNumber(value){const number=Number(value);return Number.isFinite(number)?number:0;}
function sameId(a,b){return String(a)===String(b);}
function formatDate(value){if(!value)return "—";return new Date(value).toLocaleDateString(undefined,{day:"numeric",month:"short",year:"numeric"});}
function localDateString(date=new Date()){const year=date.getFullYear();const month=String(date.getMonth()+1).padStart(2,"0");const day=String(date.getDate()).padStart(2,"0");return `${year}-${month}-${day}`;}
function App(){
  const [recordSection,setRecordSection]=useState('record');const [ratings,setRatings]=useState({});const [legacyUnrated,setLegacyUnrated]=useState([]);const [modal,setModal]=useState(null);const [detailId,setDetailId]=useState(null);const [refreshKey,setRefreshKey]=useState(0);const [overview,setOverview]=useState(null);const [archivePage,setArchivePage]=useState(1);const [theme,setTheme]=useState(()=>{try{return localStorage.getItem('gg-theme')==='golden'?'golden':'dark';}catch{return 'dark';}});const closeModal=useCallback(()=>{setModal(null);setDetailId(null);},[]);useEffect(()=>{document.documentElement.dataset.theme=theme;try{localStorage.setItem('gg-theme',theme);}catch{/* Private browsing can disable storage. */}},[theme]);useEffect(()=>{const changed=()=>setRefreshKey(n=>n+1);window.addEventListener('gg-data-changed',changed);return()=>window.removeEventListener('gg-data-changed',changed);},[]);useEffect(()=>{api('/stats/overview').then(setOverview).catch(()=>{});},[refreshKey]);function showPlayer(playerId){const player=players.find(p=>String(p._id)===String(playerId));if(player){closeModal();openPlayerProfile(player);setActiveTab(TABS.PLAYERS);}}function showMatch(matchId){setActiveTab(TABS.CALENDAR);setDetailId(matchId);setModal('match');}
  const [activeTab,setActiveTab]=useState(TABS.HOME);const [authUser,setAuthUser]=useState(null);const [backendUser,setBackendUser]=useState(null);const [authLoading,setAuthLoading]=useState(Boolean(auth));const [message,setMessage]=useState("");const [players,setPlayers]=useState([]);const [matches,setMatches]=useState([]);const [news,setNews]=useState([]);const [leaderboard,setLeaderboard]=useState([]);const [loadingPlayers,setLoadingPlayers]=useState(true);const [loadingMatches,setLoadingMatches]=useState(true);const [newsLoading,setNewsLoading]=useState(true);const [,setLeaderboardLoading]=useState(false);const [selectedPlayer,setSelectedPlayer]=useState(null);const [editingProfile,setEditingProfile]=useState(false);const [profileSaving,setProfileSaving]=useState(false);const [profileForm,setProfileForm]=useState({name:"",profileImage:"",height:"",weight:"",position:"",preferredFoot:"",jerseyNumber:"",dateOfBirth:"",bio:""});const [playerReview,setPlayerReview]=useState(null);const [playerReviewLoading,setPlayerReviewLoading]=useState(false);const [newPlayerName,setNewPlayerName]=useState("");const [playerActionLoading,setPlayerActionLoading]=useState(false);const [editingMatchId,setEditingMatchId]=useState(null);const [date,setDate]=useState(localDateString());const [matchName,setMatchName]=useState("");const [teamALabel,setTeamALabel]=useState("Team A");const [teamBLabel,setTeamBLabel]=useState("Team B");const [teams,setTeams]=useState({});const [goals,setGoals]=useState({});const [assists,setAssists]=useState({});const [ownGoals,setOwnGoals]=useState({});const [savingMatch,setSavingMatch]=useState(false);const [leaderboardPeriod,]=useState("all");const [,setPlayerOfYear]=useState(null);const [,setPlayerOfMonth]=useState(null);const today=new Date();const [calendarMonth,setCalendarMonth]=useState(today.getMonth()+1);const [calendarYear,setCalendarYear]=useState(today.getFullYear());const [calendarMatches,setCalendarMatches]=useState([]);const [calendarLoading,setCalendarLoading]=useState(false);const [hoveredDay,setHoveredDay]=useState(null);const [selectedDay,setSelectedDay]=useState(today.getDate());const [editorRequests,setEditorRequests]=useState([]);const [activeEditors,setActiveEditors]=useState([]);const [adminLoading,setAdminLoading]=useState(false);const [editorsLoading,setEditorsLoading]=useState(false);const [adminActionLoading,setAdminActionLoading]=useState(false);
  const isSignedIn=Boolean(authUser),isAdmin=backendUser?.role==="admin",isEditor=backendUser?.role==="editor"||isAdmin,hasPendingRequest=backendUser?.accessRequest==="pending";
  useEffect(()=>{if(!auth)return;const unsubscribe=onAuthStateChanged(auth,async firebaseUser=>{setAuthUser(firebaseUser);if(!firebaseUser){setBackendUser(null);setAuthLoading(false);return;}try{const token=await firebaseUser.getIdToken();const response=await fetch(`${API_URL}/auth/me`,{headers:{Authorization:`Bearer ${token}`}});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.message||`Authentication sync failed (${response.status})`);setBackendUser(data.user||null);setMessage("");}catch(error){console.error("Auth sync error:",error);setBackendUser(null);setMessage(`Could not sync your account: ${error.message}`);}finally{setAuthLoading(false);}});return unsubscribe;},[]);
  useEffect(()=>{loadPlayers();loadMatches();loadNews();loadLeaderboard("all");loadAwards();},[]);
  async function loadPlayers(){try{setLoadingPlayers(true);const response=await fetch(`${API_URL}/players`);if(!response.ok)throw new Error("Failed to load players.");const data=await response.json();setPlayers(Array.isArray(data)?data:[]);}catch(error){console.error(error);setMessage("Could not load players.");}finally{setLoadingPlayers(false);}}
  async function loadMatches(page=1){try{setLoadingMatches(true);const response=await fetch(`${API_URL}/matches?page=${page}&limit=50`);if(!response.ok)throw new Error("Failed to load matches.");const data=await response.json();const ordered=Array.isArray(data)?[...data].sort((a,b)=>new Date(b.date)-new Date(a.date)):[];setMatches(current=>page===1?ordered:[...current,...ordered]);setArchivePage(page);}catch(error){console.error(error);setMessage("Could not load matches.");}finally{setLoadingMatches(false);}}
  async function loadNews(){try{setNewsLoading(true);const response=await fetch(`${API_URL}/news?limit=12`);if(!response.ok)throw new Error("Failed to load news.");const data=await response.json();setNews(Array.isArray(data)?data:[]);}catch(error){console.error(error);setNews([]);}finally{setNewsLoading(false);}}
  async function loadLeaderboard(period="all"){try{setLeaderboardLoading(true);let url=`${API_URL}/stats/leaderboard`;const now=new Date();if(period==="year")url+=`?year=${now.getFullYear()}`;if(period==="month")url+=`?year=${now.getFullYear()}&month=${now.getMonth()+1}`;const response=await fetch(url);if(!response.ok)throw new Error("Failed to load leaderboard.");const data=await response.json();setLeaderboard(Array.isArray(data.leaderboard)?data.leaderboard:[]);}catch(error){console.error(error);setLeaderboard([]);}finally{setLeaderboardLoading(false);}}
  async function loadAwards(){try{const now=new Date(),year=now.getFullYear(),month=now.getMonth()+1;const [yearResponse,monthResponse]=await Promise.all([fetch(`${API_URL}/stats/awards?year=${year}`),fetch(`${API_URL}/stats/awards?year=${year}&month=${month}`)]);if(!yearResponse.ok||!monthResponse.ok)return;const [yearData,monthData]=await Promise.all([yearResponse.json(),monthResponse.json()]);setPlayerOfYear(yearData.winner||null);setPlayerOfMonth(monthData.winner||null);}catch(error){console.error("Awards error:",error);setPlayerOfYear(null);setPlayerOfMonth(null);}}
  async function authenticatedFetch(url,options={}){if(!auth?.currentUser)throw new Error("Authentication required.");const token=await auth.currentUser.getIdToken();return fetch(url,{...options,headers:{...(options.headers||{}),Authorization:`Bearer ${token}`}});}
  function openPlayerProfile(player){setSelectedPlayer(player);setEditingProfile(false);setPlayerReview(null);setProfileForm({name:player.name||"",profileImage:player.profileImage||"",height:player.height??"",weight:player.weight??"",position:player.position||"",preferredFoot:player.preferredFoot||"",jerseyNumber:player.jerseyNumber??"",dateOfBirth:player.dateOfBirth?new Date(player.dateOfBirth).toISOString().split("T")[0]:"",bio:player.bio||""});}
  async function loadPlayerReview(playerId){try{setPlayerReviewLoading(true);const response=await authenticatedFetch(`${API_URL}/news/player/${playerId}`,{method:"POST",headers:{"Content-Type":"application/json"}});const data=await response.json();if(!response.ok)throw new Error(data.message||"Could not generate review.");setPlayerReview(data);}catch(error){console.error(error);setMessage(error.message||"Could not generate review.");}finally{setPlayerReviewLoading(false);}}
  async function savePlayerProfile(event){event.preventDefault();if(!isEditor||!selectedPlayer){setMessage("Editor access required.");return;}try{setProfileSaving(true);const response=await authenticatedFetch(`${API_URL}/players/${selectedPlayer._id}`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(profileForm)});const data=await response.json();if(!response.ok)throw new Error(data.message||"Could not update profile.");await loadPlayers();setSelectedPlayer(data);setEditingProfile(false);invalidate();setMessage("Player profile updated.");}catch(error){console.error(error);setMessage(error.message||"Could not update profile.");}finally{setProfileSaving(false);}}
  // The remainder of App.jsx is intentionally retained by the branch history; profile rendering is updated below.
  return null;
}
export default App;
